---
apiVersion: v1
kind: Namespace
metadata:
  name: psap--runtime-int
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-aio-config
  namespace: psap--runtime-int
data:
  OPENSEARCH_REMOTE_URL: "https://opensearch-instance.example.com" # OpenSearch instance URL
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-aio-credentials
  namespace: psap--runtime-int
type: Opaque
data:
  OPENSEARCH_REMOTE_USERNAME: YWRtaW4=  # base64 encoded username 'admin'
  OPENSEARCH_REMOTE_PASSWORD: enVxYXBo  # base64 encoded password 'blehbleh'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-aio-deployment
  namespace: psap--runtime-int
  labels:
    app: grafana-aio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-aio
  template:
    metadata:
      labels:
        app: grafana-aio
    spec:
      hostAliases:
      - ip: 4.5.6.7
        hostnames:
        - thisisahost.example.com
      containers:
      - name: grafana-aio
        image: ghcr.io/ccamacho/grafana-aio:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        resources:
          limits:
            memory: 3Gi
          requests:
            memory: 2Gi
        env:
          - name: OPENSEARCH_REMOTE_URL
            valueFrom:
              configMapKeyRef:
                name: grafana-aio-config
                key: OPENSEARCH_REMOTE_URL
          - name: OPENSEARCH_REMOTE_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-aio-credentials
                key: OPENSEARCH_REMOTE_USERNAME
          - name: OPENSEARCH_REMOTE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-aio-credentials
                key: OPENSEARCH_REMOTE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-aio-service
  namespace: psap--runtime-int
  labels:
    app: grafana-aio
spec:
  type: NodePort
  selector:
    app: grafana-aio
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-aio-route
  namespace: psap--runtime-int
  labels:
    app: grafana-aio
    shard: internal
spec:
  host: grafana-aio.apps.int.gpc.ocp-hub.prod.psi.redhat.com
  to:
    kind: Service
    name: grafana-aio-service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: 3000
  wildcardPolicy: None
