---
apiVersion: v1
kind: Namespace
metadata:
  name: ccamacho-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-aio-deployment
  namespace: ccamacho-dev
spec:
  selector:
    matchLabels:
      app: grafana-aio
  template:
    metadata:
      labels:
        app: grafana-aio
    spec:
      containers:
      - name: grafana-aio
        image: ghcr.io/ccamacho/grafana-aio:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-aio-service
  namespace: ccamacho-dev
spec:
  type: NodePort
  selector:
    app: grafana-aio
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-aio-route
  namespace: ccamacho-dev
spec:
  to:
    kind: Service
    name: grafana-aio-service
    weight: 100
  port:
    targetPort: 3000
  tls:
    termination: edge
  insecurePolicy: Redirect
