---
name: publish
on: [push]
permissions:
  contents: read
  packages: write
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Buildah build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.event.repository.name }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
      - name: Push To ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
      #- name: Push to Heroku
      #  run: |
      #    curl https://cli-assets.heroku.com/install.sh | sudo sh
      #    heroku --version
      #    HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:login
      #    HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:push -a grafana-aio web
      #    HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:release -a grafana-aio web
